# Generated by Django 5.1.2 on 2024-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_question_question_text_question_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='questions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
