# Generated by Django 5.1.2 on 2024-12-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_application_questions_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='application',
            new_name='app_id',
        ),
    ]
