# Generated by Django 5.1.2 on 2024-12-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_rename_application_question_app_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='app_id',
            new_name='app',
        ),
    ]
