# Generated by Django 5.1.2 on 2024-12-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_rename_app_id_question_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_picture/'),
        ),
    ]
